<?php
$ostypeList = ['Linux', 'BSD', 'Linux/bsd'];
$basedOnList = [
                'Android',
                'Arch',
                'CentOS',
                'CRUX',
                'Debian',
                'Debian(Stable)',
                'Debian(Testing)',
                'Debian(Unstable)',
                'FFedora',
                'FrFreeBSD',
                'GGentoo',
                'IndepeIndependent',
                'KDEKDE_neon',
                'KNOPPIX',
                'LFS',
                'Mageia',
                'Mandriva',
                'Manjaro',
                'OpenBSD',
                'openSUSE',
                'PCLinuxOS',
                'Puppy',
                'Red Hat',
                'rPath',
                'sidux',
                'Slackware',
                'SliTaz',
                'Solaris',
                'Ubuntu',
                'Ubuntu(LTS)',
                'Tiny Core',
                'Zenwalk'
                ];